### ISSUE TITLE
docsy风格文档页体验问题汇总

### ISSUE THREAD

**Issue by andrewshan** [polarismesh/website#198]
## 问题1：顶层页面的banner颜色换一下，换成和下面的footer的颜色一致
![image](https://user-images.githubusercontent.com/45474304/197328315-5445c55e-b398-424f-8134-b17fe33c8f74.png)

**Comment by andrewshan** [comment]
## 问题2：左侧栏的目录太挤，显得内容太少，建议默认把第一级展开一下
![image](https://user-images.githubusercontent.com/45474304/197328589-8a5f7052-20e6-487d-8180-98ddbd8f832a.png)

**Comment by andrewshan** [comment]
## 问题3：点击文档链接会报错

![image](https://user-images.githubusercontent.com/45474304/197330838-8c00f56f-ca78-4bfa-b55c-0572e72f1539.png)

**Comment by andrewshan** [comment]
## 问题4：右边栏只保留这4个选项

![image](https://user-images.githubusercontent.com/45474304/197330943-a6f4be14-f720-4835-b0bc-299ce2251c42.png)

**Comment by andrewshan** [comment]
## 问题5：编辑此页、提交项目问题，这2个按钮不可用

![image](https://user-images.githubusercontent.com/45474304/197331012-ac13f324-2dfc-49aa-812f-516d65f844c4.png)

**Comment by andrewshan** [comment]
## 问题6：文档的子目录板块的排列风格看看能不能换成istio这种横排，然后下面带上描述的

![image](https://user-images.githubusercontent.com/45474304/197331172-a88044d6-dd35-469b-b618-20afd7fe1c5d.png)
换成
![image](https://user-images.githubusercontent.com/45474304/197331278-3762da86-91d7-43e2-8140-2bb4612d3ee1.png)

**Comment by andrewshan** [comment]
## 问题7：这里要换成北极星的logo
![image](https://user-images.githubusercontent.com/45474304/197331330-c5377e1d-3b3f-4aab-9c85-a7df9f014e78.png)

**Comment by chuntaojun** [comment]
> ## 问题5：编辑此页、提交项目问题，这2个按钮不可用
> ![image](https://user-images.githubusercontent.com/45474304/197331012-ac13f324-2dfc-49aa-812f-516d65f844c4.png)

编辑此页不可用是因为当前分支还在开发中，合并到 main 之后即可
