### ISSUE TITLE
服务注册

### ISSUE THREAD

**Issue by 1182640071** [polarismesh/website#325]
使用dubbo注册服务时，可以像使用“Java SDK”一样，精细的控制所有“[polaris.yaml配置详细](https://github.com/polarismesh/polaris-java/blob/main/polaris-common/polaris-config-default/src/main/resources/conf/default-config.yml)”么

**Comment by pengkai242** [comment]
是可以的，需要在resource下面先创建polaris.yaml。大致加载流程是：在加载dubbo-registry-polaris 插件的时候：
PolarisRegistryFactory-》PolarisRegistry-》PolarisOperator-》PolarisOperator（init）- ConfigAPIFactory.defaultConfig();
