### ISSUE TITLE
二次寻址

### ISSUE THREAD

**Issue by 1182640071** [polarismesh/website#326]
使用dubbo注册服务时，怎么配置二次寻址

**Comment by chuntaojun** [comment]
参考这个即可：https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/java%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91/sdk/%E4%BA%8C%E6%AC%A1%E5%AF%BB%E5%9D%80/
