### ISSUE TITLE
集群版安装

### ISSUE THREAD

**Issue by weiding9527** [polarismesh/website#344]
![image](https://github.com/polarismesh/website/assets/95093935/584ca7a0-2833-4309-ac52-5eccc87afe47)
教程提示下载polaris-cluster-release_$version.kubernetes.zip，但是这个文件不存在
![image](https://github.com/polarismesh/website/assets/95093935/4d779c65-defe-46fe-9e7e-bec4bc5d4aae)

**Comment by chuntaojun** [comment]
建议统一走 github release 进行下载

**Comment by chuntaojun** [comment]
后面我们会统一优化下下载地址
