### ISSUE TITLE
熔断降级

### ISSUE THREAD

**Issue by dinstone** [polarismesh/website#346]
[文档中给的例子太难懂了。这不是使用例子，看起来更新是测试的例子，难道不应该是让使用者快速了解其用法的吗？非的让读者自己领悟？](https://polarismesh.cn/docs/%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97/java%E5%BA%94%E7%94%A8%E5%BC%80%E5%8F%91/sdk/%E7%86%94%E6%96%AD%E9%99%8D%E7%BA%A7/)

由于我没有看到使用方法，所以也没法贡献文档内容。有人能讲明白吗？我可以试着简化这个例子。

**Comment by chuntaojun** [comment]
我们看下怎么调整这一块文档的介绍

**Comment by chuntaojun** [comment]
具体是那部份不太理解？

**Comment by dinstone** [comment]
> 具体是那部份不太理解？是指 SDK api 的使用方式根据这个文章还是不太理解吗

使用方式不是很清晰。一般我们会熔断一个调用，通常这个调用还是带有返回值的，应该使用的是decorator .decorateFunction（）方法装饰吧。
其次，如果方法的返回结果是个异步结果的话，还能正常工作吗？如：
decorator.decorateFunction(new Function<Call, CompletableFuture<Reply>>() {

			@Override
			public CompletableFuture<Reply> apply(Call t) {
				// TODO Auto-generated method stub
				return null;
			}
		});

**Comment by dinstone** [comment]
仔细研究了源码，发现处理异步调用的熔断方法，有需要的请参考：

``
                 ServiceKey skey = new ServiceKey(call.getGroup(), call.getService());
		RequestContext makeDecoratorRequest = new FunctionalDecoratorRequest(skey, call.getMethod());
		InvokeHandler invokeHandler = circuitBreak.makeInvokeHandler(makeDecoratorRequest);

		invokeHandler.acquirePermission();

		long startTimeMilli = System.currentTimeMillis();
		try {
			CompletableFuture<Reply> future = handler.handle(call);
			return future.whenComplete((reply, error) -> {
				long delay = System.currentTimeMillis() - startTimeMilli;

				InvokeContext.ResponseContext responseContext = new InvokeContext.ResponseContext();
				responseContext.setDuration(delay);
				responseContext.setDurationUnit(TimeUnit.MILLISECONDS);

				if (error == null) {
					responseContext.setResult(reply);
					invokeHandler.onSuccess(responseContext);
				} else {
					responseContext.setError(error);
					invokeHandler.onError(responseContext);
				}
			});
		} catch (Throwable e) {
			long delay = System.currentTimeMillis() - startTimeMilli;
			InvokeContext.ResponseContext responseContext = new InvokeContext.ResponseContext();
			responseContext.setDuration(delay);
			responseContext.setDurationUnit(TimeUnit.MILLISECONDS);
			responseContext.setError(e);
			invokeHandler.onError(responseContext);

			throw e;
		}
``

**Comment by chuntaojun** [comment]
我们也优化下熔断这里的异步化使用方式，降低用户的使用过程中的资料查找成本
