### ISSUE TITLE
集群版安装

### ISSUE THREAD

**Issue by weiding9527** [polarismesh/website#354]
![image](https://github.com/polarismesh/website/assets/95093935/a4463baf-dee4-4dd9-9e4a-1b97df994527)

下面这个polaris-$version.zip对应上图中的哪个包呢？ 我现在要使用k8s集群方式安装服务端。在kubernetes的zip包里面根本没有sql文件
![image](https://github.com/polarismesh/website/assets/95093935/7f0f78c0-692a-46b4-baa0-2eecb474a121)

**Comment by chuntaojun** [comment]
- 下载 polaris-server-release_xxx 的包获得 SQL 即可
- kubernetes 的安装包我们调整下，带上数据库的初始化脚本

**Comment by weiding9527** [comment]
1
