### ISSUE TITLE
使用开发框架

### ISSUE THREAD

**Issue by MasterSJ** [polarismesh/website#358]
sct各版本与polaris服务端版本的匹配关系是怎样的呢? 我试过使用较低版本的sct和较高版本的polaris, 部分功能生效, 但部分功能不生效. 例如: 高版本的熔断规则支持根据时延来进行熔断, 但低版本的sct中只能根据错误码进行判断, 所以配置的规则没有生效. 具体sct和polaris服务端的各版本的兼容性关系能给一下吗?

**Comment by SkyeBeFreeman** [comment]
时延熔断在SCT的1.11.0以上版本提供。SCT功能列表参考文档：https://github.com/Tencent/spring-cloud-tencent/wiki/%E5%8A%9F%E8%83%BD%E5%88%97%E8%A1%A8
