### ISSUE TITLE
Dubbo访问限流依赖拉取不到

### ISSUE THREAD

**Issue by Cloud-Yao** [polarismesh/website#363]
<dependency>
     <groupId>org.apache.dubbo.extensions</groupId>
     <artifactId>dubbo-ratelimit-polaris</artifactId>
     <version>1.0.0<version>
</dependency>

这个为啥都拉取不到啊？ 我切换成了腾讯的源，依然出现了拉取不到的情况，类似文档中依赖坐标很多地方都出现了错误，希望官网能抽个时间把文档好好整理下。

**Comment by Cloud-Yao** [comment]
<dependency>
            <groupId>com.tencent.polaris</groupId>
            <artifactId>dubbo-registry-polaris</artifactId>
            <version>0.2.2</version>
        </dependency>

        
        <dependency>
            <groupId>com.tencent.polaris</groupId>
            <artifactId>dubbo-ratelimit-polaris</artifactId>
            <version>0.2.2</version>
        </dependency>

        
        <dependency>
            <groupId>com.tencent.polaris</groupId>
            <artifactId>dubbo-router-polaris</artifactId>
            <version>0.2.2</version>
        </dependency>

        
        <dependency>
            <groupId>com.tencent.polaris</groupId>
            <artifactId>dubbo-circuitbreaker-polaris</artifactId>
            <version>0.2.2</version>
        </dependency>


这是我在maven中央仓库找到的关于dubbo插件的最新版本，求证一下官方，这个是否能直接用？和官方文档给出的dubbo插件坐标并不一样，为什么会两套不一样的dubbo插件坐标？

**Comment by chuntaojun** [comment]
https://central.sonatype.com/artifact/org.apache.dubbo.extensions/dubbo-filter-polaris-ratelimit-dubbo2/overview
