### ISSUE TITLE
Open API

### ISSUE THREAD

**Issue by 0226zy** [polarismesh/website#365]
/naming/v1/services 接口的文档描述可能有问题：
<img width="817" alt="截屏2023-09-20 15 08 55" src="https://github.com/polarismesh/website/assets/38198698/671df0ec-6db8-4f1b-99aa-2b23971fd8c7">
"export_to" 在创建时如果指定 API 会抛出错误：
request decode failed: unknown field "export_to" in v1.Service

**Comment by chuntaojun** [comment]
文档已修改，调整了描述加上了版本要求
